"""empty message

Revision ID: 714309f1f042
Revises: 7d8f682adfcf
Create Date: 2021-05-27 18:37:53.995131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714309f1f042'
down_revision = '7d8f682adfcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('createdAt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'createdAt')
    # ### end Alembic commands ###
