"""Add Firstname and Lastname to Users

Revision ID: e42953d97816
Revises: 61c66e4c91ba
Create Date: 2021-05-25 14:29:40.222947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e42953d97816'
down_revision = '61c66e4c91ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_username_key', 'users')
    op.alter_column('users', 'username', new_column_name='firstname')
    op.add_column('users', sa.Column('lastname', sa.String(length=40), nullable=True))
    op.execute("UPDATE users SET lastname = 'User'")
    op.alter_column('users', 'lastname', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'firstname', new_column_name='username')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_column('users', 'lastname')
    # ### end Alembic commands ###
